export default {
	extends: ["next/core-web-vitals"],
	env: {
		node: true,
		es6: true,
		browser: true,
		serviceworker: true,
		worker: true,
	},
	ecmaFeatures: {
		jsx: true,
	},
	plugins: [],
	parserOptions: {
		sourceType: "module",
		ecmaFeatures: {},
		ecmaVersion: "latest",
	},
	globals: {
		process: true,
		Buffer: true,
		global: true,
		window: true,
		self: true,
		globalThis: true,
		exports: true,
		module: true,
		require: true,
		console: true,
		document: true,
		localStorage: true,
		sessionStorage: true,
		navigator: true,
		XMLHttpRequest: true,
		fetch: true,
		Blob: true,
		FileReader: true,
		Image: true,
		URL: true,
		URLSearchParams: true,
		Worker: true,
		SharedWorker: true,
		performance: true,
		requestAnimationFrame: true,
		cancelAnimationFrame: true,
		requestIdleCallback: true,
		cancelIdleCallback: true,
		setImmediate: true,
		clearImmediate: true,
		Atomics: true,
		WebAssembly: true,
		SharedArrayBuffer: true,
	},
};
